### ISSUE TITLE
Fullscreen displaying issue

### ISSUE THREAD

**Issue by Gert-dev** [php-integrator/atom-tooltips#17]
From https://github.com/php-integrator/atom-base/issues/234#issuecomment-246612773

> I don't know if it's appropriate place(maybe its Atom thing), but when i go fullscreen without even tree view large hover tooltips(function desc) are often cut in half, left part goes off screen, if there was tree view everything ok this half shows over the tree, but if there are no tree view editor starts right from the left corner of the monitor and half of tooltip is only visible.
> Is it possible to limit tooltips to go only over the code and never to the left?

**Comment by maximumver** [comment]
It happens when function name is near left or bottom border of monitor.
Bigger documentation is - bigger part will be offscreen in this case.
![tooltip-bottom](https://cloud.githubusercontent.com/assets/12964203/18607567/b42f2080-7cd0-11e6-85cf-59bb332c7a14.JPG)
![left](https://cloud.githubusercontent.com/assets/12964203/18607568/b4322b22-7cd0-11e6-8597-3847f1ca049d.jpg)
